version: '3.8'

services:
  debug-consumer:
    image: rabbitmq:3-management
    depends_on:
      - rabbitmq
    command: sh -c "sleep 10 && rabbitmqadmin get queue=your_queue_name count=100"
    networks:
      - app-network
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
